# Generated by Django 4.0.4 on 2022-05-14 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_remove_arma_id_remove_municao_id_arma_id_arma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id_calibre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc_calibre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto_tipo',
            fields=[
                ('id_objeto_tipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_objeto', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='arma',
            name='marca',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='arma',
            name='modelo',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='municao',
            name='marca',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='municao',
            name='modelo',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id_objeto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objeto_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.objeto_tipo')),
            ],
        ),
        migrations.AddField(
            model_name='arma',
            name='calibre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.calibre'),
        ),
        migrations.AddField(
            model_name='arma',
            name='objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.objeto'),
        ),
        migrations.AddField(
            model_name='municao',
            name='calibre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.calibre'),
        ),
        migrations.AddField(
            model_name='municao',
            name='objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.objeto'),
        ),
    ]
